spring.application.name=demo
# Configuration du serveur
server.port=8000

# Configuration de la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant
spring.datasource.username=restaurant_user
spring.datasource.password=my_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Désactiver la validation automatique de Hibernate (car tu fais du JDBC pur)
spring.jpa.hibernate.ddl-auto=none
